import '../globals.css'
import { Inter } from 'next/font/google'

import NavigationBar from '@/components/NaviationBar'
import classNames from '@/utils/classnames'

const inter = Inter({
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<div
					className={classNames(
						inter.className,
						'flex h-screen w-screen flex-col bg-zinc-100 px-6 pt-5 md:px-16 md:pt-7'
					)}
				>
					<NavigationBar />
					{children}
				</div>
			</body>
		</html>
	)
}
