import '../globals.css'
import { Inter } from 'next/font/google'

import NavigationBar from '@/components/NaviationBar'

const inter = Inter({
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<div
					className={`${inter.className} flex h-screen w-screen flex-col bg-zinc-100 px-16 pt-7`}
				>
					<NavigationBar />
					{children}
				</div>
			</body>
		</html>
	)
}
